export type Review = {
  id: string;
  author: string;
  location: string;
  rating: number;
  date: string;
  title: string;
  body: string;
  verified: boolean;
};

export const reviewsByProduct: Record<string, Review[]> = {
  "seasonal-vegetable-box": [
    {
      id: "rv-veg-1",
      author: "Dechen Wangmo",
      location: "Thimphu",
      rating: 5,
      date: "Mar 2026",
      title: "So fresh, every week differs",
      body: "The mix changes with what is in season and everything arrived clean and ready to use. Exactly what a busy household needs.",
      verified: true,
    },
    {
      id: "rv-veg-2",
      author: "Ugyen Dorji",
      location: "Paro",
      rating: 4,
      date: "Feb 2026",
      title: "Great value for the size",
      body: "The box was generous and the vegetables were crisp. I wished the contents were confirmed a little earlier, but overall very happy.",
      verified: true,
    },
    {
      id: "rv-veg-3",
      author: "Kinley Lhamo",
      location: "Punakha",
      rating: 5,
      date: "Jan 2026",
      title: "Local produce I can trust",
      body: "Knowing the produce is Bhutanese-first makes a real difference. The family finished everything before the next box arrived.",
      verified: true,
    },
  ],
  "meal-kit-box": [
    {
      id: "rv-kit-1",
      author: "Tshewang Dema",
      location: "Thimphu",
      rating: 5,
      date: "Mar 2026",
      title: "The recipe card made it easy",
      body: "Everything was pre-portioned so I just followed the card. Dinner was on the table in under thirty minutes.",
      verified: true,
    },
    {
      id: "rv-kit-2",
      author: "Sonam Tobgay",
      location: "Thimphu",
      rating: 4,
      date: "Feb 2026",
      title: "Perfect for two",
      body: "The kit fit exactly for me and my partner. I would love more recipe options to rotate through each week.",
      verified: true,
    },
    {
      id: "rv-kit-3",
      author: "Pema Choden",
      location: "Wangdue Phodrang",
      rating: 5,
      date: "Jan 2026",
      title: "Portions were spot on",
      body: "No wasted ingredients and the flavours were great. A solid weeknight helper.",
      verified: true,
    },
  ],
  "grocery-top-up": [
    {
      id: "rv-groc-1",
      author: "Karma Yangzom",
      location: "Thimphu",
      rating: 4,
      date: "Mar 2026",
      title: "Saved me a trip to the store",
      body: "The essentials basket covered everything on my list. I would like a few more snack options next time.",
      verified: true,
    },
    {
      id: "rv-groc-2",
      author: "Dorji Tshering",
      location: "Phuentsholing",
      rating: 5,
      date: "Feb 2026",
      title: "Exactly the daily essentials",
      body: "Pantry, snacks, and household basics in one delivery. Convenient and fairly priced.",
      verified: true,
    },
    {
      id: "rv-groc-3",
      author: "Sangay Zangmo",
      location: "Thimphu",
      rating: 4,
      date: "Jan 2026",
      title: "Reliable top-up",
      body: "Good selection and nothing was missing. Delivery was on time as promised.",
      verified: true,
    },
  ],
  "fruit-box": [
    {
      id: "rv-fruit-1",
      author: "Chimi Lhamo",
      location: "Paro",
      rating: 5,
      date: "Mar 2026",
      title: "Sweet and seasonal",
      body: "The fruit selection was ripe and the ripeness guide helped us store it right.",
      verified: true,
    },
    {
      id: "rv-fruit-2",
      author: "Norbu Wangchuk",
      location: "Thimphu",
      rating: 4,
      date: "Feb 2026",
      title: "Fresh and juicy",
      body: "Everything was in great condition. I would love to see the exact selection confirmed a little earlier.",
      verified: true,
    },
    {
      id: "rv-fruit-3",
      author: "Yeshi Dem",
      location: "Punakha",
      rating: 5,
      date: "Jan 2026",
      title: "The kids finished it fast",
      body: "A lovely mix that disappeared quickly. Great quality throughout.",
      verified: true,
    },
  ],
  "breakfast-kit": [
    {
      id: "rv-brek-1",
      author: "Rinzin Pelmo",
      location: "Thimphu",
      rating: 5,
      date: "Mar 2026",
      title: "Mornings are calmer now",
      body: "Eggs, avocado, oats, and greens all portioned for one. Breakfast actually happens now.",
      verified: true,
    },
    {
      id: "rv-brek-2",
      author: "Phuntsho Wangdi",
      location: "Gelephu",
      rating: 5,
      date: "Feb 2026",
      title: "Simple and satisfying",
      body: "The recipe card took the thinking out of the first meal of the day. Will order again.",
      verified: true,
    },
    {
      id: "rv-brek-3",
      author: "Namgay Choden",
      location: "Thimphu",
      rating: 4,
      date: "Jan 2026",
      title: "Great start to the day",
      body: "Fresh ingredients and easy to prepare. A little more variety in the greens would be nice.",
      verified: true,
    },
  ],
  "high-protein-kit": [
    {
      id: "rv-prot-1",
      author: "Tandin Dorji",
      location: "Thimphu",
      rating: 5,
      date: "Mar 2026",
      title: "Hit my protein target easily",
      body: "Chicken, rice, and legumes portioned clearly. The macros were easy to track.",
      verified: true,
    },
    {
      id: "rv-prot-2",
      author: "Zangmo Wangmo",
      location: "Sarpang",
      rating: 4,
      date: "Feb 2026",
      title: "Balanced and filling",
      body: "Good portions and clean ingredients. Hoping for more sauce variety in future recipes.",
      verified: true,
    },
    {
      id: "rv-prot-3",
      author: "Karma Norbu",
      location: "Thimphu",
      rating: 5,
      date: "Jan 2026",
      title: "My training week backup",
      body: "Reliable for meal-prep days. Everything was clearly labelled.",
      verified: true,
    },
  ],
  "plant-powered-kit": [
    {
      id: "rv-plant-1",
      author: "Dechen Lhamo",
      location: "Thimphu",
      rating: 5,
      date: "Mar 2026",
      title: "Colourful and delicious",
      body: "Tofu, quinoa, and lentils made a really balanced plate. The ingredient list was reassuring.",
      verified: true,
    },
    {
      id: "rv-plant-2",
      author: "Sonam Wangmo",
      location: "Bumthang",
      rating: 5,
      date: "Feb 2026",
      title: "Best plant-based kit so far",
      body: "Everything was fresh and the recipe was simple. My favourite of the range.",
      verified: true,
    },
    {
      id: "rv-plant-3",
      author: "Ugyen Dema",
      location: "Paro",
      rating: 4,
      date: "Jan 2026",
      title: "Great flavours",
      body: "Tasty and filling. The tofu was handled well in transit.",
      verified: true,
    },
  ],
  "all-in-one-box": [
    {
      id: "rv-allin-1",
      author: "Kinley Dorji",
      location: "Thimphu",
      rating: 5,
      date: "Mar 2026",
      title: "The whole kitchen sorted",
      body: "Produce, a meal kit, and pantry basics in one box. It genuinely replaced two shopping trips.",
      verified: true,
    },
    {
      id: "rv-allin-2",
      author: "Tshewang Norbu",
      location: "Thimphu",
      rating: 5,
      date: "Feb 2026",
      title: "Great value for a household",
      body: "Everything we needed for the week arrived together. Highly recommend for families.",
      verified: true,
    },
    {
      id: "rv-allin-3",
      author: "Pema Yangzom",
      location: "Wangdue Phodrang",
      rating: 4,
      date: "Jan 2026",
      title: "Convenient bundle",
      body: "Loved the combination. I would like to pick the meal kit flavour myself.",
      verified: true,
    },
  ],
  "pantry-starter": [
    {
      id: "rv-pantry-1",
      author: "Dorji Wangmo",
      location: "Thimphu",
      rating: 5,
      date: "Mar 2026",
      title: "Kitchen ready in one go",
      body: "Oils, rice, and spices to get any kitchen going. The quality was excellent.",
      verified: true,
    },
    {
      id: "rv-pantry-2",
      author: "Sangay Tobgay",
      location: "Phuentsholing",
      rating: 4,
      date: "Feb 2026",
      title: "Good staples box",
      body: "Everything a starter kitchen needs. The spice selection could be a touch larger.",
      verified: true,
    },
    {
      id: "rv-pantry-3",
      author: "Choden Zangmo",
      location: "Thimphu",
      rating: 5,
      date: "Jan 2026",
      title: "Set us up for weeks",
      body: "Lasted longer than expected and everything was well packed.",
      verified: true,
    },
  ],
};

export function reviewsForProduct(productId: string): Review[] {
  return reviewsByProduct[productId] ?? [];
}
